# Generated by Django 3.0.3 on 2020-02-06 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(default='Carrot', max_length=600)),
                ('value', models.IntegerField(default=0)),
                ('isDead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid4', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('room_id', models.IntegerField(default=1)),
                ('num_rooms_eaten', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
