# Generated by Django 3.0.3 on 2020-02-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angry_bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Cucumber', max_length=600),
        ),
    ]
