# Generated by Django 3.0.3 on 2020-02-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angry_bugs', '0005_auto_20200206_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='Corn', max_length=600),
        ),
    ]
