# Generated by Django 3.0.3 on 2020-02-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angry_bugs', '0006_auto_20200206_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='default_type', max_length=600),
        ),
    ]
